[project]
name = "mba-ia-desafio-criacao-agente"
version = "0.1.0"
description = "Assistente Virtual do Residencial Aurora com Google ADK"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.30.1",
    "pydantic>=2.7.0",
    "python-dotenv>=1.0.1",
    "google-adk==2.2.0",
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.22.1",
    "greenlet>=3.5.6",
]

[tool.uv]
package = false
